def pokemon_directory():
    print("\n 1. Alolan Rattata")
    print(" 2. Alolan Raticate")
    print(" 3. Alolan Raichu")
    print(" 4. Alolan Sandshrew")
    print(" 5. Alolan Sandslash")
    print(" 6. Alolan Vulpix")
    print(" 7. Alolan Ninetales")
    print(" 8. Alolan Diglett")
    print(" 9. Alolan Dugtrio")
    print("10. Alolan Meowth")
    print("11. Alolan Persian")
    print("12. Alolan Geodude")
    print("13. Alolan Graveler")
    print("14. Alolan Golem")
    print("15. Alolan Grimer")
    print("16. Alolan Muk")
    print("17. Alolan Exeggutor")
    print("18. Alolan Marowak")
    print("19. Galarian Meowth")
    print("20. Galarian Perrserker")
    print("21. Galarian Ponyta")
    print("22. Galarian Rapidash")
    print("23. Galarian Slowpoke")
    print("24. Galarian Slowbro")
    print("25. Galarian Farfetched")
    print("26. Galarian Sirfetchd")
    print("27. Galarian Weezing")
    print("28. Galarian Mr.Mime")
    print("29. Galarian Mr.Rime")
    print("30. Galarian Articuno")
    print("31. Galarian Zapdos")
    print("32. Galarian Moltres")
    print("33. Galarian Slowking")
    print("34. Galarian Corsola")
    print("35. Galarian Cursola")
    print("36. Galarian Zigzagoon")
    print("37. Galarian Linoone")
    print("38. Galarian Obstagoon")
    print("39. Galarian Darumaka")
    print("40. Galarian Darmanitan")
    print("41. Galarian Yamask")
    print("42. Galarian Runerigus")
    print("43. Galarian Stunfisk")
